### ISSUE TITLE
Allow sorting in ascending and descending order

### ISSUE THREAD

**Issue by phxn** [jfurrow/flood#135]
It would be nice to be able to sort torrents in ascending and descending order.

Many thanks.

**Comment by jfurrow** [comment]
Although it's not intuitive, currently you can toggle between ascending and descending order by re-selecting the previously selected property from the "sort by" dropdown. I'll add an icon to make this more apparent.

**Comment by phxn** [comment]
Hello, this isn't the behaviour I'm seeing when doing that.

Trying to sort "Added" descending and it just stays in ascending.

**Comment by phxn** [comment]
An update on this, I noticed that I can change sort order when I manually add torrents.

However, when I send .torrents to rtorrent (with autodl-irssi for example) it won't change sort order.

**Comment by jfurrow** [comment]
Thanks for the extra information. By which property are you trying to sort the torrents? I am able to toggle the ascending and descending sort order on every property.

The only caveat to that is the date `added` property. It's only possible to sort torrents by the `added` property if the torrent has the timestamp on the custom field called `addtime`. This is custom field is used by ruTorrent, so I chose to use the same custom field in Flood. rTorrent does not set this property by default, and rTorrent does not provide a method for determining when a torrent was added. If you wish, you can configure rTorrent to add this custom key for each new torrent. If you'd like for rTorrent to set this field automatically, check out this example here: http://community.rutorrent.org/Recipe/Sort%20'incomplete'%20view%20by%20date%20added, specifically these lines:
```
# Store time when torrent is loaded into rTorrent in a custome field
system.method.set_key = event.download.inserted_new, loaded_time, "d.set_custom=tm_loaded,$cat=$system.time= ;d.save_session="
```
but note that Flood looks for `addtime` and not `tm_loaded`. Furthermore, Flood is expecting the value of `addtime` to be the number of _seconds_ since the UNIX epoch, rather than the more usual _milliseconds_ since UNIX epoch. This is how ruTorrent sets the field and I wanted to make sure Flood works reasonably well with ruTorrent.

**Comment by phxn** [comment]
Hello, thank you for the reply.

Yes I am trying to sort by "Added". In this case, would this command work?

    system.method.set_key = event.download.inserted_new, loaded_time, "d.set_custom=addtime,$cat=$system.time= ;d.save_session="

Many thanks.

**Comment by jfurrow** [comment]
@phxn Actually that `d.save_session` command won't work. But this should!
`system.method.set_key = event.download.inserted_new, loaded_time, "d.custom.set=addtime,$cat=$system.time=;d.save_full_session="`

**Comment by phxn** [comment]
Ah yes the syntax change! Thank you very much 👍
