### ISSUE TITLE
More settings

### ISSUE THREAD

**Issue by Lapin0t** [jfurrow/flood#14]
Hi, thanks for this nice project! I was tired of all these ugly php WebUIs... I'm going to start some feature-request issues to give some ideas and provide feedback.

It would be nice if the settings popup contained all the rtorrent settings (peer count, dht, pex, directories, ports...).

**Comment by jfurrow** [comment]
Thanks for filing the feature request! I'll definitely work toward mirroring rTorrent's settings — I agree, they are much-needed.

**Comment by jfurrow** [comment]
I just added some rTorrent settings — let me know what you think! They're not comprehensive, but they do include some of the settings you requested. I didn't get all of them (I skipped peer exchange and DHT settings beyond the port), but I'll finish them this week. I'll keep this issue open until that happens.

Probably the most difficult part of this process is actually understanding what the settings do and translating them into a human-friendly field label. Some of them are obvious, but some are completely foreign to me (like `throttle.max_downloads.div`). So if I've chosen labels that are unclear, please let me know. Otherwise I can read the rTorrent wiki, issues tracker, shared `rtorrent.rc` files, and (if it comes to it) the actual source code to figure out what the more obscure settings mean.

Screenshots of the new settings:
![](https://s3.amazonaws.com/f.cl.ly/items/2q1x2m3u1U2l2p1T293F/Screen%20Shot%202016-06-06%20at%209.04.38%20PM.png?v=ec5e595c)
![](https://s3.amazonaws.com/f.cl.ly/items/0j1x2s0B1U2N0t0D0n3H/Screen%20Shot%202016-06-06%20at%209.04.46%20PM.png?v=b2687d03)
![](https://s3.amazonaws.com/f.cl.ly/items/2H0j0B2m2K2n211y2J0Q/Screen%20Shot%202016-06-06%20at%209.04.52%20PM.png?v=9b5ce858)

**Comment by maximuml** [comment]
How about GeoIp and Mediainfo?

**Comment by jfurrow** [comment]
@maximuml Those would be nice additions, but I'd like to focus on exposing the core rTorrent settings. Feel free to open a separate issue for those and I'll get to them when I can!

**Comment by jfurrow** [comment]
@Lapin0t I just added DHT and peer exchange toggles. I'll keep adding more, but let me know if you'd like me to prioritize anything in particular.

**Comment by haihosilver** [comment]
Settings requests.

1. Check hash after download [ON/OFF]
2. DHT [ON/OFF]
3. Global maximum download/upload [VALUE]
4. Maximum rTorrent Memory usage in MB [VALUE]
5. RSS download manager
6. Labels
7. Auto-unpacking on matching labels

8. Maybe an "overall status-tab" showing global statistics like:
	- CPU usage
	- RAM usage
	- Disk usage
	- Global total upload
	- Global total download
	- Global total seeds
	- Global total peers
	- Other various

9. Would be great for "all" settings available in rtorrent.rc, "Advanced"-tab.

This seems like an awesome project. You could just browse all the settings and functionality(plugins) of ruTorrent and do a port of the most needed!

**Comment by sa7mon** [comment]
@haihosilver Also, it would be great if those usage stats would have a nice pretty little graphs.

**Comment by jfurrow** [comment]
Thanks! All good ideas. @sa7mon I love pretty little graphs :)

**Comment by jfurrow** [comment]
I'm going to close this as most of these features have been incorporated. Feel free to open issues for specific settings (or groups of settings if it makes sense).
