### ISSUE TITLE
Fork / alternate Backend Idea

### ISSUE THREAD

**Issue by nd4pa** [jfurrow/flood#207]
Your front-end is almost perfect, ticks are just a bit slow, what if we could rewrite de torrent client in Javascript with that : https://github.com/feross/webtorrent (i'm talking about the node lib here, the one that talks bittorrent over TCP/UDP ),  and maybe remove the time when the backend of flood talk to rtorrent over the API ?

Just an idea, i'm not that experienced, so please let me know if you agree or not, and both case, mostly, why.

Cheers.

**Comment by jfurrow** [comment]
Eventually I'd like Flood to support many different torrent clients. But because I use rTorrent, and it is already popular and works extremely well, I chose to start with rTorrent.

The UI refresh ticks should be configurable, at the very least, and in the future should make use of web sockets or similar to update pertinent data only when necessary.

For now I'll close this, but feel free to continue the discussion in the [Slack group](https://join-flood-talk.herokuapp.com/).
