### ISSUE TITLE
Feature: Manage multiple rtorrent instances

### ISSUE THREAD

**Issue by Soullivaneuh** [jfurrow/flood#413]
It's known that multiple rtorrent instance can be started on a single server.

It would be great to have the possibility to manage multiple instances on a single flood interface.

Two possibilities:

* Torrent instance selection that reload the whole interface (simpler)
* Show all torrents of all client with client filters on the left (smoother)

This features may be also useful to manage rtorrent clients on multiple servers.

**Comment by akiroz** [comment]
Just wanted to up-vote this feature because I'm currently running many dozens of rtorrent instances each with their own flood instance. rtorrent has a low-level I/O [bug][] that will make it consume all CPU resources in kernel space when you have hundreds of torrents so running a single instance is not an option....

[bug]: https://github.com/rakshasa/rtorrent/issues/535

**Comment by noraj** [comment]
duplicate of #460 (I'm closing this one because #460 have a discussion and this one seems inactive).
