### ISSUE TITLE
Stuck on first login

### ISSUE THREAD

**Issue by Jack972** [jfurrow/flood#435]
Hello,
I am trying to set up Flood on a debian 8. I am stuck at first login, on the screen "Flood Settings" remains uncheked and nothing happens. 

I have checked the following :
- rTorrent is compiled with XML-RPC support (compiled it myself with the --with-xmlrpc-c flag)
- the SCGI port or socket have been defined in rTorrent configuration (port 5000)
- tSCGI port or socket have been defined in Flood's config.js (port 3000)

Don't know what to do next.

Does anyone know a solution to fix this issue?

Thanks

**Comment by randomnonsense** [comment]
rtorrent's rpc port is the port flood communicates with it. both need to be the same. use your head. also if you can, use socket instead of tcp. Example:

flood:
```
scgi: {
    socket: true,
    socketPath: '/home/rtorrent/rtorrent.socket'
  },
```

.rtorrent.rc:
```
scgi_local = /home/rtorrent/rtorrent.socket
schedule = scgi_permission,0,0,"execute.nothrow=chmod,\"g+w,o=\",/home/rtorrent/rtorrent.socket"
```

**Comment by Jack972** [comment]
Thank you for you help, no need to be rude we don't all have the same level of understanding of this subject.

I have tried using sockets but it does not work. Still the same issue.

Here are my conf files.
**.rtorrent.rc**
`
download_rate = 0
upload_rate = 10000

max_downloads_global = 10

max_peers = 100

max_uploads = 20

directory = /home/seedbox/downloads

session = /home/seedbox/.session

port_range = 49999-49999
port_random = no

check_hash = yes

dht = auto
dht_port = 6881
peer_exchange = yes

encryption = allow_incoming,try_outgoing,enable_retry

use_udp_trackers = yes

# Port SCGI, on en a besoin pour communiquer avec Flood
scgi_local = /home/rtorrent/rtorrent.socket
schedule = scgi_permission,0,0,"execute.nothrow=chmod,\"g+w,o=\",/home/rtorrent/rtorrent.socket"
`
flood config.js
`
const CONFIG = {
  baseURI: '/',
  dbCleanInterval: 1000 * 60 * 60,
  dbPath: './server/db/',
  floodServerHost: '127.0.0.1',
  floodServerPort: 3000,
  maxHistoryStates: 30,
  pollInterval: 1000 * 5,
  secret: 'flood',
  scgi: {
    socket: true,
    socketPath: '/home/rtorrent/rtorrent.socket'
  },
  ssl: false,
  sslKey: '/absolute/path/to/key/',
  sslCert: '/absolute/path/to/certificate/',
  torrentClientPollInterval: 1000 * 2
};

module.exports = CONFIG;

`

**Comment by randomnonsense** [comment]
I am not being rude. You just don't seem to think too much about what you're doing. Check the paths. "/home/rtorrent/" is an example path. In your case this may be different. Likely "/home/seedbox/".

rtorrent is an advanced client. Flood is true work in progress. I don't think this is a solution for you. It will likely require much more tinkering and adjustments in the future and you will get stuck again. Learn the unix basics. Get back to this in the future.

**Comment by Jack972** [comment]
Well,

My rtorrent path is /home/rtorrent/ and my flood path is /home/seedbox/flood/. My rpc ports were both the same to begin with. It was not that clear in my first post, sorry about that. So far my setup looks right and your "Check the paths"... Sorry, did you get something I missed? If you do, you are not helping right now. 

I thought on places like Github I'd meet people that are into sharing knowledge anb stuff but all I can find is some pretentious prick that does not stop being rude. 

If you don't want to help, go bother someone else please.

**Comment by randomnonsense** [comment]
Oh it must be annoying, to fail at such a basic config ;-)

**Comment by jfurrow** [comment]
@randomnonsense Please be respectful. I appreciate that you're helping users, but if you can't do so without also being insulting, it's best not to contribute at all.

@Jack972 Unfortunately I don't think Github issues area a great place to ask for help like this; the Slack channel is better, but admittedly I've been kind of absent from both.

In any case, your configuration looks reasonable. Here are some things to check out:
1. Under what user account is the Flood instance running? I wonder if it doesn't have permission to the file.
2. What does Flood's server display in your terminal? Do you see a warning about not being able to connect to rTorrent?
3. What are you intending to do with this line in rtorrent.rc? `schedule = scgi_permission,0,0,"execute.nothrow=chmod,\"g+w,o=\",/home/rtorrent/rtorrent.socket"` I'd try removing this and manually configuring the socket files permissions so that both rtorrent and Flood have access.

Obviously Flood needs better documentation. Maybe one day we'll get there!

**Comment by abduct** [comment]
This looks like another permissions issue problem. 

If you are a beginner with Linux it is highly recommended to simply have flood and rtorrent share the same user, simply launch both in screen or use `&` to background the task when starting it.

Seeing as you listed two home directories I am assuming that you have two different users, one for flood, one for rtorrent. In this case you need to use less restrictive permissions on the socket file, or apply advanced groups and chown the socket file so both users share the same group permissions on the file.

Be aware that the path you're going down is going to get more tricky since flood is going to need permissions to rtorrents files it creates, and rtorrent will need access to floods files (If I recall...). Basically when rtorrent gets told to create and download a torrent it will give it rtorrent:rtorrent permissions, meanwhile flood can not access these files for deletion and other tasks. As far as I know I don't think you can config rtorrent to create files with a specific user:group without forcing the rtorrents main group to be something you custom create.

Anyways I suggest trying to launch flood on the rtorrent user and move on. Most of these issues are resolved like this.

**Comment by Jack972** [comment]
@jfurrow Thank you for your help. Sorry to bother you here, next time I check the slack channel (I didn't know there was one). I found the issue in the webserver log. Flood was unabled to joint rtorrent on port 5000. I was running rtorrent with the wrong user and thus had wrong permissions to the conf file. It is all fixed now.

@abduct Thank you for the advise. I'll think to it if I encounter more difficulties with the filesystem.

**Comment by noraj1337** [comment]
Sounds resolved. Closing.
