### ISSUE TITLE
Add/Remove torrent - No Auto-Refresh WebUI

### ISSUE THREAD

**Issue by saldru** [jfurrow/flood#56]
Hi, 

When I add or remove torrents, the WebUI will not auto-refresh and the changes are not taken into account by the interface. 
I don't know if the problem comes with my configure or not.

Thank you for your work, it's so beautiful. :)

**Comment by zp** [comment]
I've noticed there's an issue where the `emptyTorrentList` variable doesn't get changed if you add some torrent(s) when your list is empty, so you have to manually refresh.

Only thing I've noticed with removing torrents is that the # counter on the left sidebar doesn't update properly if you remove all of your remaining torrents at once. (ie, you have 2 torrents and remove them both, it still says you have 2 torrents, even after refreshing, however adding a new torrents fixes the count)

**Comment by jfurrow** [comment]
Thanks for the kind words & filing an issue! It's definitely a problem with my code and will be fixed in an upcoming update. I'll update this when that happens.

**Comment by jfurrow** [comment]
To clarify, the torrent list was being fetched when torrents were added (but not when they were removed — that's fixed by this PR: https://github.com/jfurrow/flood/pull/57). However, rTorrent itself takes some time to report newly added/removed torrents, especially when the list of torrents is large. I have 1600+ torrents running and it sometimes takes several several seconds for rTorrent's torrent list to reflect these updates.

In the future, I would like to optimistically update the UI, but this will take some careful considerations and will likely not be implemented for some time.
