### ISSUE TITLE
Pixel XL 3 displaying squished desktop view

### ISSUE THREAD

**Issue by robertbaker** [jfurrow/flood#758]
![screenshot_20190125-111805](https://user-images.githubusercontent.com/907301/51764771-3f8d0a80-2093-11e9-9cef-5eb863d72130.png)

Is this expected on a mobile device? Not very usable.

**Comment by noraj** [comment]
Hi @robertbaker 

Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.

```markdown
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:

## Summary
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- (Optional) Tell us what should happen -->

## Current Behavior
<!--- (Optional) Tell us what happens instead of the expected behavior -->

## Possible Solution
<!--- (Optional) suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- (Optional) What are you trying to accomplish? -->
```

I'm closing the issue until you fill it.

Feel free to ask to re-open it as soon as it's done.

**Comment by fsamareanu** [comment]
@robertbaker: it’s quite usable in landscape. Portrait indeed makes things hard.

**Comment by robertbaker** [comment]
Make a better issue template that is little ridiculous for a lot of little issues like this. Also just be aware that no one gets here issue templates when they use a mobile device

**Comment by robertbaker** [comment]
> @robertbaker: it’s quite usable in landscape. Portrait indeed makes things hard.

Is it like this for all mobile devices? Is there no proper mobile views??

**Comment by robertbaker** [comment]
@noraj done.

Consider forking this project if you're a react dev because it appears to be dead. From experience, it's unlikely Jfurrow it's going to work on this again. I know that he wants to and doesn't want to 'give up', but it's not going to happen. I'm not sure continuing development in a repo under his name would be the best idea unless you have admin rights. It's going to be hard to find contributors at this point anyway, so idk if it's worth it.

**Comment by noraj** [comment]
@robertbaker 

> Consider a smaller template, that is little much if want people to fill it out

All our template are very small except the bug one that is medium size but all info are required to troubleshoot correctly, sorry.

> Also just be aware that no one gets the issue templates when they use a mobile device

Flood is installed on a server (or more rarely a computer), you are troubleshooting on either the server or the computer, you're expected to fill the issue on your computer not your mobile device.
And it is a github issue if issue template are not displaying on mobile not a flood one.

> @noraj done.

No done, please fill **Your Environment** correctly.

```markdown
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:
```

`master` is not a commit id, `latest` is not a version and hugely depends on your OS and its version, and OS can't be `N.A.`.

**Comment by noraj** [comment]
@robertbaker Please also read the [CODE_OF_CONDUCT](https://github.com/jfurrow/flood/blob/master/CODE_OF_CONDUCT.md) and do not PM people on discord, you have the issue tracker and the discord server to do so.

**Comment by noraj** [comment]
@robertbaker 

> Consider forking this project if you're a react dev because it appears to be dead. From experience, it's unlikely Jfurrow it's going to work on this again. I know that he wants to and doesn't want to 'give up', but it's not going to happen. I'm not sure continuing development in a repo under his name would be the best idea unless you have admin rights. It's going to be hard to find contributors at this point anyway, so idk if it's worth it.

1) This is not the right issue to talk about that, let's talk in #672 and #712
2) Rather than inviting people to fork ask them to join the Organization (see #672) and ask @jfurrow to transfer this repository to the organization

**Comment by robertbaker** [comment]
I use docker, yes I build it from master everyday. Honestly my OS and version, etc don't matter as this is clearly not environment specific.

I don't know what you are talking about with discord....I didn't message anyone.

It's clear that development is all but dead and getting petty over issue templates when this is clearly an issue with enough info really puts me off. I'm done with this project.

**Comment by noraj** [comment]
@robertbaker 

> I use docker, yes I build it from master everyday.

So you should have write docker before, this is clearly important.

> don't matter as this is clearly not environment specific or version specific

False, commit id is important because you can talk about something already fixed for example, and yes environment and version are important because it can change the version of dependencies, that can change the final output or break something.
Still nodejs 11.x or latest is not a version, for example `v11.6.0` is. Also npm version is different from nodejs version, npm 11 doesn't even exist, for example I have npm `6.6.0`.

> I don't know what you are talking about with discord....I didn't message anyone.

Sorry for discord I thought it was you, timing coincidence:

![image](https://user-images.githubusercontent.com/16578570/51800955-a4816580-2237-11e9-966b-9693d216ea97.png)

> It's clear that development is all but dead and getting petty over issue templates when this is clearly an issue with enough info really puts me off. Instead of fixing things, you want to be pedantic over what are simple bugs. I'm done with this project.

1) Yes development is quite dead because there is only 1 dev that is @jfurrow, I'm not a dev I'm just here to help managing issues, project management and gibing security advice.
2) No, there was not enough information, as I said commit ID, node and npm version and OS are very important even if you don't understand why. Without that it is impossible to troubleshoot.
3) Yes I won't fix this because I'm not a dev. I know a little about ruby but nothing about javascript.
4) I'm not pedantic, I'm assuring there is enough information to troubleshot, because just saying "It won't work" or just pasting a screenshot is clearly not enough to do anything.
5) I'm sorry but I'm spending my free time here just to help and you are very aggressive with me. Also this is a free, libre and open-source project, not a proprietary and paid product where you bought some support or anything. There is no warranty. If you think that development is to slow, please learn the JavaScript language and come help @jfurrow.
6) About the template being to heavy that's why we slit issues by category. Here, we know now this is not a bug, so you should have open a **Feature Request** issue with a much lighter template.

I'm sorry I'll lock this conversation as this is just you being aggressive and not constructive and violating the code of conduct.
