### ISSUE TITLE
Improve torrent-detail/general tab

### ISSUE THREAD

**Issue by mahoek** [jfurrow/flood#76]
I was thinking about improving the torrent-detail/general tab.
```
General
Added:              July 10, 2016 11:07 AM
Location:           path/to/download
Scheduler:          Obeyed/ignored
Tags:               <tag1> <tag2> <tag3>

Transfer
Downloaded:         1% (630KB/63MB)
Peers:              0 of 2 connected
Seeds:              0 of 233 connected

Torrent
Size:               63MB
Hash:               883C6F02FC46188AC17EA49C13C3E9D97413A5A2
Creation date:      June 04, 2016 6:58 PM
Comment:            <torrent comment>
Type:               Public/private

Tracker
Tracker message:    <tracker message>
```
I think that free disk space should not be in the torrent detail modal. Maybe the sidebar is a better place? 

And what about the tracker information? Should it be here or on the Tracker tabs?

Your thoughts and suggestions would be highly appreciated.

**Comment by jfurrow** [comment]
We have discussed some of this in Slack, but I'll add my feedback here:
1. I agree that disk space is a more global statistic. However, rTorrent itself considers it a per-torrent statistic. I think this is because rTorrent is reporting the available space on the disk which contains that torrent's data (I think — maybe I'm wrong about this). So if we were to display free disk space in the sidebar, we would need to display the data for all disks on the host, which could be a significant number of disks. So I think this needs to be explored in mockups.
2. For the "tracker" details, the benefit to being displayed on the "details" tab is that it's one less click away from the user. But, because the "tracker message" is used to report errors (as far as I can tell), it would probably be a lot more useful if it were displayed as a tooltip on the error icon in the torrent list when an error is detected. So, for now, I'm leaning toward leaving it on the "details" tab. If you feel strongly that it should be on the "tracker" tab, then that's fine with me too!

**Comment by mahoek** [comment]
1. In the meantime, while we haven't moved the free disk space to the sidebar, do you think we should let it in the general tab?
2. I agree. I'll let it on the general tab for now. We can move that later.

**Comment by jfurrow** [comment]
1. Yes, I do think it should stay in this tab for now.
2. Cool :)

**Comment by jfurrow** [comment]
I'm considering this closed for now, great work!
